spring.application.name=saloon_app

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://ep-steep-thunder-ahkv52r1-pooler.c-3.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_WcgQB0VoZYi4

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api

spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=30MB


#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.tool.hbm2ddl=DEBUG
#logging.level.org.springframework.orm.jpa=DEBUG

